# simplefb
lib-$(CONFIG_SIMPLE_FB) += simplefb/simplefb.o

# video
lib-$(CONFIG_SIMPLE_FB) += video/font.o

# debug
lib-y += debug/debug.o

# unic (neatlibc still temporarily resides)
lib-y += unic/string.o
