# the drivers registration framework
lib-y += framework.o
lib-$(CONFIG_LIBFDT) += ramdisk-handler.o
lib-$(CONFIG_EXYNOS_ACPM) += samsung/exynos-acpm.o
lib-$(CONFIG_EXYNOS_SPEEDY) += samsung/exynos-speedy.o
