# the drivers registration framework
lib-y += framework.o
lib-$(CONFIG_LIBFDT) += ramdisk-handler.o
lib-$(CONFIG_EXYNOS_ACPM) += samsung/exynos-acpm.o
lib-$(CONFIG_EXYNOS_SPEEDY) += samsung/exynos-speedy.o
lib-$(CONFIG_MEDIATEK_MCUSYS) += mediatek/mcusys.o
lib-$(CONFIG_TIMER_MTK_CPUXGPT) += timer/mtk_cpuxgpt.o
