lib-$(CONFIG_APPLE_T7000) += apple/t7000.o
lib-$(CONFIG_EXYNOS_7885) += exynos/exynos7885.o
lib-$(CONFIG_EXYNOS_8895) += exynos/exynos8895.o
lib-$(CONFIG_EXYNOS_9810) += exynos/exynos9810.o
lib-$(CONFIG_EXYNOS_9825) += exynos/exynos9825.o
