# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025 Ivaylo Ivanov <ivo.ivanov.ivanov1@gmail.com>

obj-$(CONFIG_POSITION_INDEPENDENT) += aarch64/reloc.o
obj-y += aarch64/start.o aarch64/memcpy.o
